async def help_cmd(update: Update, context: ContextTypes.DEFAULT_TYPE):
    await update.message.reply_text(
        "📌 Help – 다국어 안내\n\n"

        "[한국어]\n"
        "/createcode       – 3일 무료 코드 생성 (중복 불가)\n"
        "/registercode [코드] – 그룹에 코드 등록 (등록 즉시 3일 타이머)\n"
        "/disconnect       – 연결 해제 (등록 정보 완전 삭제)\n"
        "/solomode         – 솔로 모드 시작 (1:1 채팅, 3일간)\n"
        "/extendcode       – 그룹 코드 30일 연장 요청 (최대 2회)\n"
        "/remaining        – 남은 기간 조회 (일·시간·분 단위)\n"
        "/paymentcheck     – USDT 결제 자동 확인 및 연장\n\n"

        "[English]\n"
        "/createcode       – Create a 3-day free code (no duplicates)\n"
        "/registercode [code] – Register code to this group (starts 3-day timer)\n"
        "/disconnect       – Disconnect and delete registration\n"
        "/solomode         – Start solo mode (1:1 chat, 3 days)\n"
        "/extendcode       – Request 30-day extension (max 2 times)\n"
        "/remaining        – Check remaining time (days/hours/minutes)\n"
        "/paymentcheck     – Auto-check USDT payment & extend\n\n"

        "[中文]\n"
        "/createcode       – 生成 3 天免费代码（不重复）\n"
        "/registercode [代码] – 在本群注册代码（启动3天计时）\n"
        "/disconnect       – 取消连接并删除注册信息\n"
        "/solomode         – 开始独唱模式（1:1 聊天，3 天）\n"
        "/extendcode       – 请求延长 30 天（最多 2 次）\n"
        "/remaining        – 查询剩余时间（日/时/分）\n"
        "/paymentcheck     – 自动检查 USDT 支付并延长\n\n"

        "[ភាសាខ្មែរ]\n"
        "/createcode       – បង្កើតកូដឥតគិតថ្លៃ 3 ថ្ងៃ (មិនម្តងទៀត)\n"
        "/registercode [កូដ] – ចុះបញ្ជីកូដទៅក្រុមនេះ (ចាប់ផ្តើមគិតម៉ោង​3ថ្ងៃ)\n"
        "/disconnect       – តភ្ជាប់ឡើងវិញ និងលុបព័ត៌មានចុះឈ្មោះ\n"
        "/solomode         – ចាប់ផ្តើម Solo Mode (ប្រាស្រ័យទាក់ទង១:១, 3 ថ្ងៃ)\n"
        "/extendcode       – ស្នើសុំពន្យារពេល 30 ថ្ងៃ (អតិបរមា 2 ដង)\n"
        "/remaining        – ពិនិត្យពេលនៅសល់ (ថ្ងៃ/ម៉ោង/នាទី)\n"
        "/paymentcheck     – ពិនិត្យការទូទាត់ USDT ដោយស្វ័យប្រវត្តិ & ពន្យារ\n\n"

        "[Tiếng Việt]\n"
        "/createcode       – Tạo mã miễn phí 3 ngày (không trùng)\n"
        "/registercode [mã] – Đăng ký mã cho nhóm này (bắt đầu bộ đếm 3 ngày)\n"
        "/disconnect       – Ngắt kết nối và xóa đăng ký\n"
        "/solomode         – Bật chế độ solo (chat 1:1, 3 ngày)\n"
        "/extendcode       – Yêu cầu gia hạn 30 ngày (tối đa 2 lần)\n"
        "/remaining        – Kiểm tra thời gian còn lại (ngày/giờ/phút)\n"
        "/paymentcheck     – Tự động kiểm tra thanh toán USDT & gia hạn"
    )
